package me.hypherionmc.modexporter.common.commands;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import com.mojang.brigadier.context.CommandContext;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import me.hypherionmc.modexporter.utils.HastebinAPI;
import net.minecraft.command.CommandSource;
import net.minecraft.command.Commands;
import net.minecraft.command.arguments.MessageArgument;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.TranslationTextComponent;
import net.minecraftforge.fml.ModList;
import org.apache.commons.io.FileUtils;

import java.io.File;
import java.nio.charset.StandardCharsets;

public class ModListExportCommand {

    public static void register(CommandDispatcher<CommandSource> dispatcher) {
        LiteralArgumentBuilder<CommandSource> modlistExportCommand =
                Commands.literal("modlist")
                .requires((commandSource -> commandSource.hasPermissionLevel(4)))
                .then(Commands.argument("type", MessageArgument.message()).executes(ModListExportCommand::exportModlist));

        dispatcher.register(modlistExportCommand);
    }

    private static int exportModlist(CommandContext<CommandSource> context) throws CommandSyntaxException {
        ITextComponent type = MessageArgument.getMessage(context, "type");
        String typeString = type.getString();

        if (typeString.equalsIgnoreCase("file")) {

            StringBuilder builder = new StringBuilder();
            builder.append("<h2>Installed Mods</h2>").append(System.lineSeparator());
            builder.append("<ul>").append(System.lineSeparator());

            ModList.get().getMods().forEach(mod -> {
                if (!mod.getDisplayName().equalsIgnoreCase("minecraft") && !mod.getDisplayName().equalsIgnoreCase("forge")) {
                    builder.append("<li>").append(mod.getDisplayName()).append(" - ").append(mod.getOwningFile().getFile().getFileName()).append("</li>").append(System.lineSeparator());
                }
            });

            builder.append("</ul>").append(System.lineSeparator());
            builder.append("Generated by Mod Exporter");

            try {
                FileUtils.writeStringToFile(new File("modlist-export.html"), builder.toString(), StandardCharsets.UTF_8);
                context.getSource().sendFeedback(new TranslationTextComponent("commands.modlist.exported"), true);
                return 1;
            } catch (Exception e) {
                e.printStackTrace();
                context.getSource().sendErrorMessage(new TranslationTextComponent("commands.modlist.failed"));
            }

        } else if (typeString.equalsIgnoreCase("paste")) {
            StringBuilder builder = new StringBuilder();
            builder.append("Installed Mods").append(System.lineSeparator());

            ModList.get().getMods().forEach(mod -> {
                if (!mod.getDisplayName().equalsIgnoreCase("minecraft") && !mod.getDisplayName().equalsIgnoreCase("forge")) {
                    builder.append(mod.getDisplayName()).append(" - ").append(mod.getOwningFile().getFile().getFileName()).append(System.lineSeparator());
                }
            });

            builder.append("Generated by Mod Exporter");

            String pasteUrl = HastebinAPI.addToPaste(builder.toString());
            if (pasteUrl.isEmpty()) {
                context.getSource().sendErrorMessage(new TranslationTextComponent("commands.modlist.pastefail"));
            } else {
                String pasteTranslated = new TranslationTextComponent("commands.modlist.pasted").getString().replace("${url}", pasteUrl);
                context.getSource().sendFeedback(new TranslationTextComponent(pasteTranslated), true);
            }
        } else {
            context.getSource().sendFeedback(new TranslationTextComponent("commands.modlist.usage"), false);
        }
        return 1;

    }
}
