modLoader = "javafml" #mandatory
loaderVersion = "[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
issueTrackerURL="https://github.com/hypherionmc/mod-exporter/issues" #optional
[[mods]] #mandatory
modId = "modexporter" #mandatory
version = "1.17.x-${file.jarVersion}" #mandatory
displayName = "Mod Exporter" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile="modexporter_logo.png" #optional
authors="HypherionSA" #optional
description = '''
A simple utility mod for exporting your modlist to a file or hastebin
'''

[[dependencies.modexporter]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[37,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.modexporter]]
modId = "minecraft"
mandatory = true
versionRange = "1.17.1"
ordering = "NONE"
side = "BOTH"
